import React, { useState } from 'react'
import { Bell, Send, Loader2, CheckCircle, AlertCircle, Info } from 'lucide-react'
import toast from 'react-hot-toast'

async function sendTelegramTestMessage(botToken, chatId) {
  const resp = await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      chat_id: chatId,
      text:
        '🤖 *AutoCommit Generator — Test Message*\n\n✅ Your Telegram bot is connected and working!\n\n_Sent from the dashboard_',
      parse_mode: 'Markdown',
    }),
  })
  const data = await resp.json()
  if (!data.ok) throw new Error(data.description || 'Telegram API error')
  return data
}

export default function NotificationsPage({ config }) {
  const [botToken, setBotToken]   = useState('')
  const [chatId, setChatId]       = useState('')
  const [sending, setSending]     = useState(false)
  const [lastResult, setLastResult] = useState(null)

  const handleTest = async () => {
    if (!botToken || !chatId) {
      toast.error('Enter both Bot Token and Chat ID first')
      return
    }
    setSending(true)
    setLastResult(null)
    try {
      await sendTelegramTestMessage(botToken, chatId)
      setLastResult({ ok: true, msg: 'Test message sent successfully!' })
      toast.success('Telegram test message sent!')
    } catch (err) {
      setLastResult({ ok: false, msg: err.message })
      toast.error(`Telegram error: ${err.message}`)
    } finally {
      setSending(false)
    }
  }

  const telegramDay = config?.telegram_report_day ?? 'Tuesday'
  const telegramHour = config?.telegram_report_hour_ist ?? 9

  return (
    <div className="space-y-4 animate-fade-in">
      {/* Header */}
      <div className="flex items-center gap-2 pb-1">
        <Bell size={20} className="text-fg-muted" />
        <div>
          <h2 className="text-lg font-semibold text-fg">Notifications</h2>
          <p className="text-xs text-fg-muted">Telegram bot configuration and weekly reports</p>
        </div>
      </div>

      {/* Weekly report info */}
      <div className="card">
        <div className="section-title mb-3">📅 Weekly Report Schedule</div>
        <div className="grid grid-cols-2 gap-3 text-sm">
          <div>
            <div className="text-xs text-fg-muted">Sends every</div>
            <div className="font-semibold text-fg mt-0.5">{telegramDay}</div>
          </div>
          <div>
            <div className="text-xs text-fg-muted">At (IST)</div>
            <div className="font-semibold text-fg mt-0.5">{telegramHour}:00 IST</div>
          </div>
        </div>

        <div className="mt-4 space-y-2 text-xs text-fg-muted">
          <div className="flex items-start gap-2">
            <CheckCircle size={13} className="text-success-fg flex-shrink-0 mt-0.5" />
            <span>Current streak + longest streak</span>
          </div>
          <div className="flex items-start gap-2">
            <CheckCircle size={13} className="text-success-fg flex-shrink-0 mt-0.5" />
            <span>Total commits fired this week (Mon–Sun)</span>
          </div>
          <div className="flex items-start gap-2">
            <CheckCircle size={13} className="text-success-fg flex-shrink-0 mt-0.5" />
            <span>Quality score with status indicator</span>
          </div>
          <div className="flex items-start gap-2">
            <CheckCircle size={13} className="text-success-fg flex-shrink-0 mt-0.5" />
            <span>Next week's scheduled rest days preview</span>
          </div>
          <div className="flex items-start gap-2">
            <CheckCircle size={13} className="text-success-fg flex-shrink-0 mt-0.5" />
            <span>Attached PDF report (generated by ReportLab)</span>
          </div>
          <div className="flex items-start gap-2">
            <CheckCircle size={13} className="text-success-fg flex-shrink-0 mt-0.5" />
            <span>Streak break warning if no commit by 8pm IST</span>
          </div>
        </div>
      </div>

      {/* Test connection */}
      <div className="card">
        <div className="section-title mb-3">🧪 Test Telegram Connection</div>
        <div className="text-xs text-fg-muted mb-4">
          The actual bot token and chat ID are stored as GitHub Secrets — they are never exposed in the dashboard.
          Enter them here temporarily to send a test message.
        </div>

        <div className="space-y-3 mb-4">
          <div>
            <label className="block text-xs font-medium text-fg-muted mb-1.5">
              Bot Token (from @BotFather)
            </label>
            <input
              id="input-bot-token"
              type="password"
              value={botToken}
              onChange={e => setBotToken(e.target.value)}
              placeholder="123456789:ABCdef..."
              className="w-full bg-canvas-inset border border-border rounded-lg px-3 py-2 text-sm text-fg font-mono placeholder:text-fg-subtle focus:outline-none focus:border-accent-fg transition-colors"
            />
          </div>
          <div>
            <label className="block text-xs font-medium text-fg-muted mb-1.5">
              Chat ID (your personal chat)
            </label>
            <input
              id="input-chat-id"
              type="text"
              value={chatId}
              onChange={e => setChatId(e.target.value)}
              placeholder="987654321"
              className="w-full bg-canvas-inset border border-border rounded-lg px-3 py-2 text-sm text-fg font-mono placeholder:text-fg-subtle focus:outline-none focus:border-accent-fg transition-colors"
            />
          </div>
        </div>

        <button
          id="btn-test-telegram"
          onClick={handleTest}
          disabled={sending || !botToken || !chatId}
          className="btn btn-accent w-full justify-center"
        >
          {sending ? (
            <><Loader2 size={15} className="animate-spin" /> Sending…</>
          ) : (
            <><Send size={15} /> Send Test Message</>
          )}
        </button>

        {lastResult && (
          <div className={`
            mt-3 flex items-start gap-2 p-3 rounded-lg text-xs
            ${lastResult.ok ? 'bg-success-muted text-success-fg' : 'bg-danger-muted text-danger-fg'}
          `}>
            {lastResult.ok ? <CheckCircle size={13} className="flex-shrink-0 mt-0.5" /> : <AlertCircle size={13} className="flex-shrink-0 mt-0.5" />}
            <span>{lastResult.msg}</span>
          </div>
        )}
      </div>

      {/* Setup guide */}
      <div className="card">
        <div className="section-title mb-3">⚙️ Telegram Setup Guide</div>
        <ol className="space-y-3 text-sm text-fg-muted">
          {[
            'Open Telegram → search @BotFather → send /newbot → choose a name → copy the Bot Token.',
            'Send any message to your new bot → open https://api.telegram.org/bot{TOKEN}/getUpdates → copy your Chat ID from the response.',
            'In your GitHub project repo → Settings → Secrets → Actions → add TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID.',
            'Done. The workflow reads these secrets automatically on every Tuesday run.',
          ].map((step, i) => (
            <li key={i} className="flex gap-3">
              <span className="flex-shrink-0 w-5 h-5 rounded-full bg-accent-muted text-accent-fg text-xs flex items-center justify-center font-bold">
                {i + 1}
              </span>
              <span>{step}</span>
            </li>
          ))}
        </ol>
      </div>
    </div>
  )
}
